/* 
 * InventoryAPI
 *
 * Orkiv Inventory API client 
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.InventoryClient.Api;
using IO.InventoryClient.Model;
using IO.InventoryClient.Client;
using System.Reflection;

namespace IO.InventoryClient.Test
{
    /// <summary>
    ///  Class for testing EventRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class EventRequestTests
    {
        // TODO uncomment below to declare an instance variable for EventRequest
        //private EventRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of EventRequest
            //instance = new EventRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EventRequest
        /// </summary>
        [Test]
        public void EventRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" EventRequest
            //Assert.IsInstanceOfType<EventRequest> (instance, "variable 'instance' is a EventRequest");
        }

        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Test]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }
        /// <summary>
        /// Test the property 'Serviceid'
        /// </summary>
        [Test]
        public void ServiceidTest()
        {
            // TODO unit test for the property 'Serviceid'
        }
        /// <summary>
        /// Test the property 'Postbody'
        /// </summary>
        [Test]
        public void PostbodyTest()
        {
            // TODO unit test for the property 'Postbody'
        }

    }

}
