/* 
 * InventoryAPI
 *
 * Orkiv Inventory API client 
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.InventoryClient.Api;
using IO.InventoryClient.Model;
using IO.InventoryClient.Client;
using System.Reflection;

namespace IO.InventoryClient.Test
{
    /// <summary>
    ///  Class for testing OrderRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class OrderRequestTests
    {
        // TODO uncomment below to declare an instance variable for OrderRequest
        //private OrderRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of OrderRequest
            //instance = new OrderRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of OrderRequest
        /// </summary>
        [Test]
        public void OrderRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" OrderRequest
            //Assert.IsInstanceOfType<OrderRequest> (instance, "variable 'instance' is a OrderRequest");
        }

        /// <summary>
        /// Test the property 'OrderId'
        /// </summary>
        [Test]
        public void OrderIdTest()
        {
            // TODO unit test for the property 'OrderId'
        }
        /// <summary>
        /// Test the property 'InfoEmail'
        /// </summary>
        [Test]
        public void InfoEmailTest()
        {
            // TODO unit test for the property 'InfoEmail'
        }
        /// <summary>
        /// Test the property 'InfoFirst'
        /// </summary>
        [Test]
        public void InfoFirstTest()
        {
            // TODO unit test for the property 'InfoFirst'
        }
        /// <summary>
        /// Test the property 'InfoLast'
        /// </summary>
        [Test]
        public void InfoLastTest()
        {
            // TODO unit test for the property 'InfoLast'
        }
        /// <summary>
        /// Test the property 'Phone'
        /// </summary>
        [Test]
        public void PhoneTest()
        {
            // TODO unit test for the property 'Phone'
        }
        /// <summary>
        /// Test the property 'Shipset'
        /// </summary>
        [Test]
        public void ShipsetTest()
        {
            // TODO unit test for the property 'Shipset'
        }
        /// <summary>
        /// Test the property 'InfoAdr1'
        /// </summary>
        [Test]
        public void InfoAdr1Test()
        {
            // TODO unit test for the property 'InfoAdr1'
        }
        /// <summary>
        /// Test the property 'InfoAdr2'
        /// </summary>
        [Test]
        public void InfoAdr2Test()
        {
            // TODO unit test for the property 'InfoAdr2'
        }
        /// <summary>
        /// Test the property 'InfoCty'
        /// </summary>
        [Test]
        public void InfoCtyTest()
        {
            // TODO unit test for the property 'InfoCty'
        }
        /// <summary>
        /// Test the property 'InfoZip'
        /// </summary>
        [Test]
        public void InfoZipTest()
        {
            // TODO unit test for the property 'InfoZip'
        }
        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Test]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }
        /// <summary>
        /// Test the property 'InfoSadr1'
        /// </summary>
        [Test]
        public void InfoSadr1Test()
        {
            // TODO unit test for the property 'InfoSadr1'
        }
        /// <summary>
        /// Test the property 'InfoSadr2'
        /// </summary>
        [Test]
        public void InfoSadr2Test()
        {
            // TODO unit test for the property 'InfoSadr2'
        }
        /// <summary>
        /// Test the property 'InfoScty'
        /// </summary>
        [Test]
        public void InfoSctyTest()
        {
            // TODO unit test for the property 'InfoScty'
        }
        /// <summary>
        /// Test the property 'InfoSzip'
        /// </summary>
        [Test]
        public void InfoSzipTest()
        {
            // TODO unit test for the property 'InfoSzip'
        }
        /// <summary>
        /// Test the property 'Sstate'
        /// </summary>
        [Test]
        public void SstateTest()
        {
            // TODO unit test for the property 'Sstate'
        }
        /// <summary>
        /// Test the property 'TaxAmount'
        /// </summary>
        [Test]
        public void TaxAmountTest()
        {
            // TODO unit test for the property 'TaxAmount'
        }
        /// <summary>
        /// Test the property 'ShippingAmount'
        /// </summary>
        [Test]
        public void ShippingAmountTest()
        {
            // TODO unit test for the property 'ShippingAmount'
        }
        /// <summary>
        /// Test the property 'AmountTotal'
        /// </summary>
        [Test]
        public void AmountTotalTest()
        {
            // TODO unit test for the property 'AmountTotal'
        }

    }

}
